version: 2.1

orbs:
  unity: game-ci/unity@1.1.0

pre-steps:
    il2cpp: &il2cpp
      - checkout
      - run:
          name: "Change the ProjectSettings.asset to use il2cpp"
          command: |
            perl -pi -e 's/scriptingBackend.*\n/scriptingBackend:/' src/ProjectSettings/ProjectSettings.asset
            perl -pi -e 's/scriptingBackend.*/scriptingBackend:\n    Standalone: 1/' src/ProjectSettings/ProjectSettings.asset
            grep -A 2 scriptingBackend src/ProjectSettings/ProjectSettings.asset
            git config --global user.email "ericribeiro@outlook.com.br"
            git config --global user.name "Eric Ribeiro"
            git add -A
            git commit -m "Change the ProjectSettings.asset to use il2cpp"
    webgl: &webgl
    # Useful for playing the project in the CircleCI web app
    # Makes sharing and testing the project easier
      - checkout
      - run:
          name: "Turn off WebGL compression"
          command: |
            perl -pi -e 's/webGLCompressionFormat.*/webGLCompressionFormat: 2/' src/ProjectSettings/ProjectSettings.asset
            grep -A 2 webGLCompressionFormat src/ProjectSettings/ProjectSettings.asset
            git config --global user.email "ericribeiro@outlook.com.br"
            git config --global user.name "Eric Ribeiro"
            git add -A
            git commit -m "Turn off WebGL compression"

workflows:
  build-unity-project:
    jobs:
      # Create the Unity activation license file
      # You only need this if you are using the Personal license
      # More info: https://game.ci/docs/circleci/activation#personal-license
      - unity/create-activation-file:
          name: "create-activation-file"

      # Run tests in playmode for Linux, Windows and macOS
      # More info: https://game.ci/docs/circleci/test
      - unity/test:
          name: "test-linux"
          step-name: "Check if the tests run and results are uploaded"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.9f1"
            resource_class: "medium"
          project-path: "src"
          test-platform: "playmode"
          context: cpe-unity
      - unity/test:
          name: "test-windows"
          step-name: "Check if the tests run and results are uploaded"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/windows-2019"
            size: "large"
            editor_version: "2021.3.2f1"
            target_platform: "windows-il2cpp"
          project-path: "src"
          test-platform: "playmode"
          context: cpe-unity
      - unity/test:
          name: "test-osx"
          step-name: "Check if the tests run and results are uploaded"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/macos"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          test-platform: "playmode"
          context: cpe-unity

      # Build for several platforms using Mono for the scripting backend
      # More info: https://game.ci/docs/circleci/build  
      - unity/build:
          name: "build-linux64-mono"
          step-name: "Build StandaloneLinux64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "base"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          build-target: StandaloneLinux64
          compress: true
          context: cpe-unity
      - unity/build:
          name: "build-Windows64-mono"
          step-name: "Build StandaloneWindows64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "windows-mono"
            editor_version: "2021.3.2f1"
            resource_class: "large"
          project-path: "src"
          build-target: "StandaloneWindows64"
          context: cpe-unity
      - unity/build:
          name: "build-osx-mono"
          step-name: "Build StandaloneOSX"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "mac-mono"
            editor_version: "2021.3.2f1"
            resource_class: "large"
          project-path: "src"
          build-target: "StandaloneOSX"
          context: cpe-unity

      # Build for several platforms using IL2CPP for the scripting backend
      # More info: https://game.ci/docs/circleci/build  
      - unity/build:
          name: "build-linux64-il2cpp"
          step-name: "Build StandaloneLinux64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          build-target: StandaloneLinux64
          compress: true
          context: cpe-unity
          pre-steps: *il2cpp
      - unity/build:
          name: "build-Windows64-il2cpp"
          step-name: "Build StandaloneWindows64 il2cpp"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/windows-2019"
            size: "large"
            editor_version: "2021.3.2f1"
            target_platform: "windows-il2cpp"
          project-path: "src"
          build-target: StandaloneWindows64
          compress: true
          context: cpe-unity
          pre-steps: *il2cpp
      - unity/build:
          name: "build-osx-il2cpp"
          step-name: "Build macOS IL2CPP"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/macos"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          build-target: StandaloneOSX
          compress: true
          context: cpe-unity
          pre-steps: *il2cpp

      # Build for several other platforms
      - unity/build:
          name: "build-webgl"
          step-name: "Build WebGL"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "webgl"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          build-target: "WebGL"
          compress: false
          context: cpe-unity
          pre-steps: *webgl
      - unity/build:
          name: "build-android"
          step-name: "Build Android"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "android"
            editor_version: "2021.3.2f1"
            resource_class: "large"
          project-path: "src"
          build-target: "Android"
          context: cpe-unity
      - unity/build:
          name: "build-ios"
          step-name: "Build iOS"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "ios"
            editor_version: "2021.3.2f1"
            resource_class: "large"
          project-path: "src"
          build-target: "iOS"
          context: cpe-unity
      - unity/build:
          name: "build-tvOS"
          step-name: "Build Apple's tvOS"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/windows-2019"
            size: "large"
            editor_version: "2021.3.2f1"
            target_platform: "appletv"
          project-path: "src"
          build-target: tvOS
          compress: true
          context: cpe-unity