version: 2.1

orbs:
  unity: ericribeiro/unity@dev:alpha

jobs:
  prepare-env:
    docker:
      - image: ubuntu-2021.2.7f1-linux-il2cpp-1
      
    steps:
      - run:
          name: "Prepare environment for activation."
          command: |
            activate_license_path="${CIRCLE_WORKING_DIRECTORY/\~/$HOME}/_activate-license~"
            encoded_unity_license="${!ACTIVATION_ULF_ENC}"
            decoded_unity_license=$(printf '%s' "$encoded_unity_license" | base64 --decode)

            mkdir -p "$activate_license_path"

            printf '%s' "export ACTIVATE_LICENSE_PATH=$activate_license_path" >> $BASH_ENV
            printf '%s' "export UNITY_LICENSE=$decoded_unity_license" >> $BASH_ENV

workflows:
  test:
    jobs:
      - prepare-env
      - unity/activate
      - unity/test:
          matrix:
            parameters:
              tag: [ "ubuntu-2021.2.7f1-linux-il2cpp-1" ]
          test-platform: "PlayMode"
          verbose: true