version: 2.1
executors:
  unity:
    docker:
      - image: unityci/editor:2021.2.7f1-mac-mono-0.15
commands:
  activate:
    steps:
      - run:
          name: "Activate Unity Licence File"
          command: |
            if [[ -z $"ACTIVATION_ULF_ENC" ]]; then
              echo "ACTIVATION_ULF_ENC is missing. You must provide the base64 encoded ULF licence file contents."
              exit 1
            fi

            echo
            echo "Decoding and writing licence file to /root/Unity_lic.ulf"
            echo

            echo "$ACTIVATION_ULF_ENC" | base64 --decode > /root/Unity_lic.ulf
            /opt/unity/Editor/Unity -batchmode -manualLicenseFile /root/Unity_lic.ulf -logfile /dev/stdout || true

            echo "Unity exit code: $?" 
  run_tests:
    steps:
      - run:
          name: Testing
          command: |
            set -x

            ${UNITY_EXECUTABLE:-xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/unity/Editor/Unity} \
              -projectPath $(pwd)/src \
              -runTests \
              -testPlatform PlayMode \
              -testResults ./results.xml \
              -logFile /dev/stdout \
              -batchmode

            UNITY_EXIT_CODE=$?

            if [ $UNITY_EXIT_CODE -eq 0 ]; then
              echo "Run succeeded, no failures occurred";
            elif [ $UNITY_EXIT_CODE -eq 2 ]; then
              echo "Run succeeded, some tests failed";
            elif [ $UNITY_EXIT_CODE -eq 3 ]; then
              echo "Run failure (other failure)";
            else
              echo "Unexpected exit code $UNITY_EXIT_CODE";
            fi

            cat src/results.xml
            cat src/results.xml | grep test-run | grep Passed
            exit $UNITY_TEST_EXIT_CODE
            
jobs:
  UnityTests:
    executor: unity
    steps:
      - checkout
      - activate
      - run_tests

workflows:
  Unity_Test_Deploy:
    jobs:
      - UnityTests