version: 2.1
orbs:
  unity: ericribeiro/unity@dev:alpha
workflows:
  test:
    jobs:
      - unity/test:
          matrix:
            parameters:
              tag: [ "ubuntu-2021.2.7f1-linux-il2cpp-1" ]
          test-platform: "PlayMode"
          license: "ACTIVATION_ULF_ENC"
          verbose: true
      - unity/build:
          matrix:
            parameters:
              tag: [ "ubuntu-2021.2.7f1-linux-il2cpp-1" ]
          project-path: "src"
          build-target: StandaloneLinux64
          build-method: "UnityBuilderAction.Builder.BuildProject"
          build-artifact-path: build
          build-artifact-filename: PotatoGame
          build-version: 0.0.1
          build-name: PotatoGameBuild
          verbose: true
          license: "ACTIVATION_ULF_ENC"