version: 2.1

orbs:
  unity: game-ci/unity@0.1.0

workflows:
  test_and_build:
    jobs:
      - unity/test:
          name: "test-2021"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          executor:
              name: "unity/ubuntu-2021"
              target-platform: "linux-il2cpp"
          project-path: "src"
          test-platform: "playmode"
          context: unity-orb-testing
      - unity/build:
          name: "build-linux64-2021"
          step-name: "Build StandaloneLinux64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          executor:
              name: "unity/ubuntu-2021"
              target-platform: "linux-il2cpp"
          project-path: "src"
          build-target: StandaloneLinux64
          compress: true
          requires:
            - test-2021
          context: unity-orb-testing
      - unity/build:
          name: "build-webgl-2021"
          step-name: "Build WebGL"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          executor:
              name: "unity/ubuntu-2021"
              target-platform: "webgl"
          project-path: "src"
          build-target: "WebGL"
          compress: false
          requires:
            - test-2021
          context: unity-orb-testing
      - unity/build:
          name: "build-windows64-2021"
          step-name: "Build StandaloneWindows64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE_2021"
          executor:
              name: "unity/ubuntu-2021"
              target-platform: "windows-mono"
          project-path: "src"
          build-target: "StandaloneWindows64"
          requires:
            - test-2021
          context: unity-orb-testing
 