version: 2.1
orbs:
  unity: ericribeiro/unity@dev:alpha
executor: << parameters.tag >>
workflows:
  test:
    jobs:
      - unity/test:
          test-platform: "PlayMode"
          matrix:
            parameters:
              tag: [ "2021.2.7f1-mac-mono-0.15", "2021.2.7f1-windows-mono-0.15", "2021.2.7f1-android-0.15.0"]