version: 2.1

orbs:
  unity: ericribeiro/unity@dev:alpha

workflows:
  test:
    jobs:
      - unity/activate:
          unity-license-var-name: "ACTIVATION_ULF_ENC"
      - unity/test:
          matrix:
            parameters:
              tag: [ "ubuntu-2021.2.7f1-linux-il2cpp-1" ]
          test-platform: "PlayMode"
          verbose: true
          requires:
            - unity/activate