version: 2.1

orbs:
  unity: ericribeiro/unity@dev:alpha

workflows:
  test:
    jobs:
      # - unity/build:
      #     license: "ACTIVATION_ULF_ENC"
      #     matrix:
      #       parameters:
      #         tag: [ "ubuntu-2021.2.7f1-linux-il2cpp-1" ]
      #     project-path: "src"
      #     build-target: StandaloneLinux64
      - unity/build:
          license: "ACTIVATION_ULF_ENC"
          matrix:
            parameters:
              tag: [ "ubuntu-2021.2.7f1-linux-il2cpp-1" ]
          project-path: "src"
          test-platform: "editmode"